# Site Settings
title: Ryan Parker
email: ryanpark88.rp@gmail.com
description: >
  Getting started with Jekyll.
baseurl: ''
url: 'http://RyanPark88.github.io'
twitter_username: RyanParkR
github_username: RyanPark88
# Build Settings
css:
  css_dir: style.css
include: ['script.js']
input: GFM
